In [55]:
print(" * ASSIGNMENT_NUMPY_BASIC *")

 * ASSIGNMENT_NUMPY_BASIC *


In [54]:
import numpy as np

In [33]:
list_ = ['1' , '2' , '3' , '4' , '5']

In [56]:
array_list = np.array(object = list_)

In [35]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
print("Q_1_ANS :- Well, the main difference between List and ArrayList is that List is an interface while ArrayList is a class. Most importantly, it implements the List interface, which also means that ArrayList is a subtype of the List interface. ")

Q_1_ANS :- Well, the main difference between List and ArrayList is that List is an interface while ArrayList is a class. Most importantly, it implements the List interface, which also means that ArrayList is a subtype of the List interface. 


In [68]:
print(type(array_list))

<class 'numpy.ndarray'>


In [26]:
print(type(list_))

<class 'list'>


In [70]:
array_list.dtype

dtype('<U1')

In [48]:
print("Q_2_ANS :- print data type using variable list_ \n print data type using variable array_list  ")

Q_2_ANS :- print data type using variable list_ 
 print data type using variable array_list  


In [50]:
 #print data type using variable list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [57]:
#print data type using variable array_list
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [49]:
print("Q_3_ANS :-  print data type using variable list_ \n print data type using variable array_list ")

Q_3_ANS :-  print data type using variable list_ 
 print data type using variable array_list 


In [38]:
array_list = np.array(object=list_, dtype=int)

In [52]:
 #print data type using variable list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [53]:
#print data type using variable array_list
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [41]:
print("Q_4_ANS :- ")

Q_4_ANS :- 


In [42]:
num_list = [[1,2,3] , [4,5,6]]

In [43]:
num_array = np.array(object = num_list)

In [44]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
num_array.shape

(2, 3)

In [46]:
num_array.size

6

In [60]:
print("Q_5_ANS :- created matrix of 3*3 ")

Q_5_ANS :- created matrix of 3*3 


In [71]:
np.array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [63]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
print("Q_6_ANS :- created identical matrix ")

Q_6_ANS :- created identical matrix 


In [65]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])